kafka:
  boot-server: localhost:29092
  topic-name: product-v1
  consumer-group-id: formationkafka-example-consumer-groupeId
  client-id: microservice-apiprice-consumer #important, c'est le nom du microservice
  # applicationId = client-id
server:
  port: 8084