kafka:
  boot-server: localhost:29092
  topic-name: price-v1
  consumer-group-id: microservice-apiprice-consumer-groupeId
  client-id: microservice-apiprice-consumer #important, c'est le nom du microservice
  # applicationId = client-id
server:
  port: 8084
spring:
  application:
    name: microservice-apiprice-consumer
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 127.0.0.1:9300
