spring:
  port: 8085
  application:
    name: microservice-apiprice

  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27017
      database: dbprice
      repositories:
        enabled: true
