spring:
  application:
    name: microservice-apiprice
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27017
      database: dbprice
server:
  port: 8085

# kafka
kafka:
  bootstrap-server: localhost:29092 #bootstrap.servers=<BOOTSTRAP_SERVER>
  acks: all
  retries: 2  # retry=2147483647
  batch-size: 131072
  buffer-memory: 80000000
  client-id: producerEvent
  idempotence: true
  compression-type: snappy
  topic-name: deleted-price-v1
  user: producer-user
  password: producer-pwd
  max-in-flight-requests-per-connection: 5
  auto-register-schemas: false

camel:
  springboot:
    name: formation-apache-camel

in:
  directory: /home/alex/Documents/formation/talend/dossier_JSON/
  file:
    filemask: .*.[json|JSON]